### ISSUE TITLE
Add support for credential helper

### ISSUE THREAD

**Issue by kyoh86** [go-git/go-git#250] opened 2021-01-31 15:25 UTC
Would it be possible to add support for the `git credential` helpers?

**Comment by mih-kopylov** [comment] 2023-06-04 05:02
Does this look like a duplicate of #490 ?
If yes, then let's close it.

**Comment by pjbgf** [comment] 2023-06-04 07:49
Closing this in favour of #490, which is more descriptive.

**Closed by pjbgf** 2023-06-04 07:49 UTC
Labels: duplicate
