### ISSUE TITLE
Filtering logs with a filename is very slow

### ISSUE THREAD

**Issue by aptituz** [go-git/go-git#137] opened 2020-07-17 10:13 UTC
Hi,

today I tried to use the library in one of my projects to get the history of a specific file and figured that iterating over the commits is extremely slow when specifying a FileName in the `LogOptions`.

With slow I mean that in my use case it took almost **30 seconds** to get log entries for a single file in a repo that has around 3000 commits, is 33 MB in size and consists mostly of yaml files. In contrast, listing _all_ commits of that repository without the filtering takes less than a second.

For reproducing the issue i built a very small example tool based on go-git, that I attached to the ticket. 
After building it can be executed like this (or by omitting the last argument to get all commits):

`
time ./git-test /path/to/repo file_in_repo
`
The issue can be easily reproduced running that tool against the go-git source itself, for example like this:

`
time ./git-test /path/to/go-git-workpath prune.go
`

On my machine that took  19 seconds (HEAD being 641ee1dd69d3b8616127623e4b9341f4f4196d12 in that test), while listing all commits again takes less than a second. Before that, I tried running it against a fresh clone of the kubernetes repo and aborted it after a few minutes, so that didn't make a good test case.

In my tests it didn't make a difference to specify a since-date to limit the amount of commits affected, probably because the code seems to iterate over filename specifications first.

Best Regards,
Patrick

[git-test.zip](https://github.com/go-git/go-git/files/4937061/git-test.zip)

**Comment by aptituz** [comment] 2020-07-17 10:32
One thing probably also worth mentioning is that it's heavily using cpu time. I'm having a Macbook with a 2,3 GHz Quad-Core Intel Core i5 and running the tool above made the fan go crazy and the activity monitor in MacOS showing around 150% cpu usage constantly.

**Comment by klingtnet** [comment] 2020-07-23 09:16
I can confirm this issue for `github.com/go-git/go-git/v5 v5.1.0` with `go 1.14.6` on Linux.

**Comment by klingtnet** [comment] 2020-07-24 07:29
I modified @aptituz example a bit to benchmark the available search algorithms:

```go
	repo, err := gogit.PlainOpen(repoPath)
	if err != nil {
		log.Fatalf("Failed to init repo %q: %s", repoPath, err.Error())
	}

	orders := []gogit.LogOrder{gogit.LogOrderDefault, gogit.LogOrderCommitterTime, gogit.LogOrderDFS, gogit.LogOrderDFSPost, gogit.LogOrderBSF}
	sort.Slice(orders, func(i, j int) bool { return int8(orders[i]) < int8(orders[j]) })
	for _, order := range orders {
		now := time.Now()
		gitlog, err := repo.Log(&gogit.LogOptions{FileName: &filename, Order: order})
		if err != nil {
			log.Fatal("repo.Log:", err)
		}
		commit, err := gitlog.Next()
		if err != nil {
			log.Fatal("log.Next:", err)
		}
		elapsed := time.Since(now)
		fmt.Printf("time elapsed for order %d: %s\n", order, elapsed)
		log.Println(commit.ID())
	}
```

Here's the result when used on `github.com/go-git/go-git CODE_OF_CONDUCT.md` (it was the oldest file I found):

```sh
$ go run main.go ../go-git CODE_OF_CONDUCT.md
time elapsed for order 0: 1.374492609s
2020/07/24 09:26:17 e9037637fbcf832e0325a3884d9ae360c3c4dc2c
time elapsed for order 1: 1.324231199s
2020/07/24 09:26:18 e9037637fbcf832e0325a3884d9ae360c3c4dc2c
time elapsed for order 2: 714.399466ms
2020/07/24 09:26:19 afdd28d3cfe11c280723c4f5f33845fd415350d6
time elapsed for order 3: 5.563808061s
2020/07/24 09:26:25 e9037637fbcf832e0325a3884d9ae360c3c4dc2c
time elapsed for order 4: 3.807974558s
2020/07/24 09:26:28 afdd28d3cfe11c280723c4f5f33845fd415350d6
```

The fastest ordering is `gogit.LogOrderDFSPost` (2).  Note that not all the orderings found the same commit ID.

**Comment by zfLQ2qx2** [comment] 2020-07-28 00:37
@klingtnet I noticed the speed difference - plus I'm getting two to three results returned that git log <filename> does not return and which do not contain modifications for the file. Changing the search order gives different results but none match git log. I think there is a short circuit missing someplace. So far I haven't found a way to differentiate the valid and invalid results aside form manually comparing with git log.

**Comment by laszlocph** [comment] 2021-01-22 12:38
Did a little investigation. The time is spent in [getNextFileCommit](https://github.com/go-git/go-git/blob/master/plumbing/object/commit_walker_path.go#L59) in calling `changes, diffErr := DiffTree(currentTree, parentTree)`

It diffs the full repository file tree. Which in my case takes 40ms per commit.
The speed is a function of the number of files in the repo.

If we could limit the trees that are compared, we could speed this up.

**Comment by SpencerMalone** [comment] 2021-02-01 19:53
In my very legacy repo w/ ~300k commits, neither the above implementation from laszlocph nor the current implementation are performant (they both take 4 minutes or more per iterator step). I'm trying to view the last 20ish commits to a specific file, but it's surprisingly frustrating to find this as such a large blocker to utilizing go-git

**Comment by WoLfulus** [comment] 2022-12-01 00:19
This is unusable in its current state. Can confirm this is taking a lot of time even for small repositories.

**Comment by SuperSandro2000** [comment] 2023-11-11 15:13
.

**Comment by pjbgf** [comment] 2023-11-13 11:19
Closing this as a duplicate of https://github.com/go-git/go-git/issues/811.

**Closed by pjbgf** 2023-11-13 11:19 UTC
