### ISSUE TITLE
close tcp 10.244.1.157:55258->18.205.93.0:22: use of closed network connection

### ISSUE THREAD

**Issue by rjdp** [go-git/go-git#70] opened 2020-05-21 07:35 UTC
I am using Argo workflow which uses `gopkg.in/src-d/go-git.v4` . I am using git clone via ssh
The 2 related github issues are:

- https://github.com/src-d/go-git/issues/1033

- https://github.com/argoproj/argo/issues/1457

Some closure will be really helpful. Thanks :)

**Comment by dcu** [comment] 2021-03-24 21:19
any news about this? we're having the same issue

**Comment by dcu** [comment] 2021-03-25 16:03
I found the cause of this is closing the client here: https://github.com/go-git/go-git/blob/master/plumbing/transport/ssh/common.go#L94
besides I believe that client is shared because it's ssh.DefaultClient

**Comment by dcu** [comment] 2021-03-26 15:02
I fixed this issue in #272 I prevented it from failing when the connection was already closed because according to a comment in the same code it is an expected behavior

**Comment by nikoremi97** [comment] 2021-03-26 15:19
Thanks, it worked pretty well @dcu! I used your fork while the PR is approved using a replace in the go.mod
I used this:
`replace github.com/go-git/go-git/v5 => github.com/dcu/go-git/v5 v5.2.1-0.20210325181450-3e3eda06723b
`

**Closed** 2021-03-26 16:02 UTC
