### ISSUE TITLE
Git log extremely slow when applied to a file

### ISSUE THREAD

**Issue by romain-gaillard** [go-git/go-git#811] opened 2023-07-14 16:15 UTC
I am trying to get a list of commits in which a given file has been modified.

Therefore, I'm doing a `Log` and I set `FileName` to my file in the `LogOptions`.
But this process is very slow. In the following example, it takes about a minute to return, whereas using git in command line returns immediately.

```go
package main

import (
	"fmt"

	"github.com/go-git/go-billy/v5/memfs"
	git "github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing/object"
	"github.com/go-git/go-git/v5/storage/memory"
)

func main() {
	fs := memfs.New()

	fmt.Println("Cloning repository")

	rep, _ := git.Clone(memory.NewStorage(), fs, &git.CloneOptions{
		URL: "https://www.github.com/sigmahq/sigma",
	})

	f := "README.md"

	fmt.Println("git log")
	cIter, _ := rep.Log(&git.LogOptions{FileName: &f})

	_ = cIter.ForEach(func(c *object.Commit) error {

		return nil
	})

	fmt.Println("Finished")
}
```

Also, the same example just browsing all the commits, not filtering on a given file returns immediately.

```go
package main

import (
	"fmt"

	"github.com/go-git/go-billy/v5/memfs"
	git "github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing/object"
	"github.com/go-git/go-git/v5/storage/memory"
)

func main() {
	fs := memfs.New()

	fmt.Println("Cloning repository")

	rep, _ := git.Clone(memory.NewStorage(), fs, &git.CloneOptions{
		URL: "https://www.github.com/sigmahq/sigma",
	})

	//f := "README.md"

	fmt.Println("git log")
	cIter, _ := rep.Log(&git.LogOptions{})

	_ = cIter.ForEach(func(c *object.Commit) error {

		return nil
	})

	fmt.Println("Finished")
}
```

Can this be improved? If not, what workaround can I use to get the list of commits that modified a given file with better performance?

**Comment by qaqland** [comment] 2023-08-05 14:41
meet the same sloooooooooooooow

gitea is using git cmd: https://github.com/go-gitea/gitea/blob/main/modules/git/repo_commit.go#L244

**Comment by pjbgf** [comment] 2023-10-09 22:04
@romain-gaillard I had a look on the code and I believe the issue is that without setting a file name, the logic is fairly simple - iterate through all commits.

Now when a file is provided, for each commit we iterate, its tree needs to be decoded and compared with the previous one. Then we loop through all the changed files to see if they have the same name. So simply put, there is definitely room for improvement here, which would short-circuit some of the heavy lifting.

Anyone keen on fixing this issue, please tag me on the PR and I will be happy to review it.

**Comment by onee-only** [comment] 2024-03-12 00:27
I created PR that partially resolves this. But I'm not sure if this is fast enough compared to git cmd.

**Comment by pjbgf** [comment] 2024-03-12 07:49
Closing as per #1046. If new reports arise (ideally with some performance stats), we can re-open or simply create a new issue.

**Closed by pjbgf** 2024-03-12 07:49 UTC
Labels: bug, good first issue, help wanted, performance
