### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by MasonXon** [go-git/go-git#1121] opened 2024-06-20 08:52 UTC
```shell
fatal error: concurrent map read and map write

goroutine 14 [running]:
github.com/go-git/go-git/v5/plumbing/format/idxfile.(*MemoryIndex).FindHash(0x1406d38e008, 0x122c4d73)
    /Users/example/GolandProjects/pkg/mod/github.com/go-git/go-git/v5@v5.11.0/plumbing/format/idxfile/idxfile.go:177 +0x54
github.com/go-git/go-git/v5/plumbing/format/packfile.(*Packfile).GetByOffset(0x1403ccdcc60, 0x122c4d73)
    /Users/example/GolandProjects/pkg/mod/github.com/go-git/go-git/v5@v5.11.0/plumbing/format/packfile/packfile.go:91 +0x34
github.com/go-git/go-git/v5/storage/filesystem.(*ObjectStorage).decodeObjectAt(0x1402b66e7a8, 0x1403ccdcc60, 0x122c4d73)
    /Users/example/GolandProjects/pkg/mod/github.com/go-git/go-git/v5@v5.11.0/storage/filesystem/object.go:498 +0xf0
github.com/go-git/go-git/v5/storage/filesystem.(*ObjectStorage).getFromPackfile(0x1402b66e7a8, {0x25, 0xf7, 0x65, 0x94, 0xde, 0x34, 0x4f, 0xe7, 0xcc, ...}, ...)
    /Users/example/GolandProjects/pkg/mod/github.com/go-git/go-git/v5@v5.11.0/storage/filesystem/object.go:479 +0x21c
github.com/go-git/go-git/v5/storage/filesystem.(*ObjectStorage).EncodedObject(0x1402b66e7a8, 0x1, {0x25, 0xf7, 0x65, 0x94, 0xde, 0x34, 0x4f, 0xe7, ...})
    /Users/example/GolandProjects/pkg/mod/github.com/go-git/go-git/v5@v5.11.0/storage/filesystem/object.go:331 +0x44
github.com/go-git/go-git/v5/plumbing/storer.(*EncodedObjectLookupIter).Next(0x140689bc8c0)
    /Users/example/GolandProjects/pkg/mod/github.com/go-git/go-git/v5@v5.11.0/plumbing/storer/object.go:152 +0x7c
github.com/go-git/go-git/v5/plumbing/object.(*storerCommitIter).Next(0x14063da8640)
    /Users/example/GolandProjects/pkg/mod/github.com/go-git/go-git/v5@v5.11.0/plumbing/object/commit.go:483 +0x30
github.com/go-git/go-git/v5/plumbing/object.(*commitPreIterator).Next(0x14094c2e4e0)
    /Users/example/GolandProjects/pkg/mod/github.com/go-git/go-git/v5@v5.11.0/plumbing/object/commit_walker.go:57 +0x84
github.com/go-git/go-git/v5/plumbing/object.(*commitPreIterator).ForEach(0x14094c2e4e0, 0x1403cc880e0)
    /Users/example/GolandProjects/pkg/mod/github.com/go-git/go-git/v5@v5.11.0/plumbing/object/commit_walker.go:97 +0x2c
git2json/repo.(*Git).showCommits(0x1402bb55080, 0x1402bb55140)
    /Users/example/GolandProjects/git2json/repo/git.go:106 +0x234
created by git2json/repo.(*Git).CommitInfoCollect in goroutine 11
    /Users/example/GolandProjects/git2json/repo/git.go:31 +0x118
```

The above error will be caused when concurrently reading the git repos. Hope to add locks to avoid this problem.

**Comment by pjbgf** [comment] 2024-06-28 21:13
Closing as duplicate of #208 and #773.

**Closed by pjbgf** 2024-06-28 21:13 UTC
