### ISSUE TITLE
malformed unpack status: 0024unpack index-pack abnormal exit

### ISSUE THREAD

**Issue by petar** [go-git/go-git#725] opened 2023-03-28 20:22 UTC
I am experiencing a seemingly flaky behavior with git push, which occurs only when pushing to GitHub (and not to local on-disk repos). Sometimes I get an error `malformed unpack status: 0024unpack index-pack abnormal exit`, and sometimes it works fine.

For reference: https://github.com/social4git/social4git/issues/5

The bug does not seem to be on my end of the code. But for context: My code constructs a git tree (by merging some existing trees), creates a new commit for the tree, updates a branch ref to point to the new commit, and then pushes.

**Comment by dathan** [comment] 2023-04-04 02:31
I too am getting this error
```
malformed unpack status: 006b001dunpack index-pack failed
0045ng refs/heads/master error processing packfiles: exit status 128
0000

```


when pushing to github,


My Author object is the following

```
// Commit the changes
_, err = w.Commit(content, &git.CommitOptions{
		Author: &object.Signature{
			Name:  "bot",
			Email: "dathanvp+gptgitsave@gmail.com",
			When:  time.Now(),
		},
})
```

**Comment by Jmainguy** [comment] 2023-04-04 02:58
:+1:  getting the same issue

```
tf-github-fake-repo-name-repos encountered an error, malformed unpack status: 007e001dunpack index-pack failed
0058ng refs/heads/githug-assistant-metadata error processing packfiles: exit status 128
```

My push options are same as dathan's, also pushing to github.

**Comment by choejwoo** [comment] 2023-04-04 11:23
Can you check object after commit the changes like an example in 
https://github.com/go-git/go-git/blob/master/_examples/commit/main.go
```
	Info("git commit -m \"example go-git commit\"")
	commit, err := w.Commit("example go-git commit", &git.CommitOptions{
		Author: &object.Signature{
			Name:  "John Doe",
			Email: "john@doe.org",
			When:  time.Now(),
		},
	})

	CheckIfError(err)

	// Prints the current HEAD to verify that all worked well.
	Info("git show -s")
	obj, err := r.CommitObject(commit)
	CheckIfError(err)

	fmt.Println(obj)
...
```
Use `fmt.Println(obj)` to check object data.

**Comment by Jmainguy** [comment] 2023-04-04 13:11
```
commit 5b292aa6a34f273d06920a5c9d9bf17ef5339b49
Author: githug-assistant <githug-assistant@company.com>
Date:   Tue Apr 04 09:09:25 2023 -0400

    Update metadata

tf-github-company-repos encountered an error, malformed unpack status: 007e001dunpack index-pack failed
0058ng refs/heads/githug-assistant-metadata error processing packfiles: exit status 128
0000
```

**Comment by cottonball** [comment] 2023-04-04 18:28
Thanks @Jmainguy!

 FYI, Slack convo:
https://github.slack.com/archives/C12RL65A9/p1680631839538979

**Comment by dathan** [comment] 2023-04-04 23:54
I can confirm that @Jmainguy downgrade does indeed solve the problem for me.
$ go get -u github.com/go-git/go-git/v5@v5.5.2

**Comment by spraints** [comment] 2023-04-05 21:10
>     unpack index-pack failed

👋🏻 I wanted to let you know that at least one of the issues here was a bug that we introduced on GitHub.com this week as a part of some changes to the server end of `git push`. The bug particularly affects go-git because go-git always includes push-options, even if the list is empty, and our new implementation didn't handle push options correctly. (See https://github.com/github/spokes-receive-pack/pull/40.) We rolled back to the old implementation at 2023-04-04 18:15 UTC. We verified the fix and are going to start rolling out the new code again over the next couple of days. I'll keep an eye on this issue while we do that, please post if you notice anything!

**Comment by spraints** [comment] 2023-04-12 12:52
Last week, we also found the source of `malformed unpack status` errors that go-git sometimes reported, and fixed that.

We've had our new push backend rolled out for a couple of days now, and everything looks good on our end. This issue looks like it can be closed now. Sorry for the trouble!

**Comment by pjbgf** [comment] 2023-04-24 21:52
@spraints thank you very much for sharing both comments above. Closing the issue for the time being, happy to reopen if it needs be.

**Closed by pjbgf** 2023-04-24 21:52 UTC
