### ISSUE TITLE
Support cloning between go-git repositories

### ISSUE THREAD

**Issue by weberc2-tempus** [go-git/go-git#823] opened 2023-08-01 16:48 UTC
In order to test some code which uses `go-git` to clone, I would like to create an in-memory upstream repository with `go-git` and then clone it into an in-memory downstream repository using the code under test. This seems to be impossible currently because `Clone()` takes a filesystem which it assumes to be a chroot into the target worktree directory which means passing `CloneOptions{URL: "../sibling"}` or similar doesn't work because the worktree directory is in a chroot (when I've tried this with the following code, I get a `repository not found` error).

*Ideally* we could clone between go-git repositories that are on fully distinct filesystems (without bringing in a heavyweight network dependency), but for the immediate case a completely local clone (i.e., "PlainClone()" but abstracting away the `osfs` dependency) would be sufficient.

```go
func TestCloneFromGoGitRepo(t *testing.T) {
	// create a single memfs with `/upstream` and `/worktree` directories.
	fs := memfs.New()
	if err := fs.MkdirAll("upstream", 0755); err != nil {
		t.Fatalf("creating `/upstream` directory: %v", err)
	}
	if err := fs.MkdirAll("worktree", 0755); err != nil {
		t.Fatalf("creating `/worktree` directory: %v", err)
	}

	// initialize a bare repo for `/upstream`
	upstreamFS, err := fs.Chroot("/upstream")
	if err != nil {
		t.Fatalf("creating the `upstream` chroot: %v", err)
	}
	if _, err := git.Init(
		filesystem.NewStorage(upstreamFS, cache.NewObjectLRUDefault()),
		nil,
	); err != nil {
		t.Fatalf("initializing upstream git repo: %v", err)
	}

	// clone from the upstream repo to the downstream worktree
	worktreeFS, err := fs.Chroot("/worktree")
	if err != nil {
		t.Fatalf("creating the `worktree` chroot: %v", err)
	}
	if _, err := git.Clone(
		memory.NewStorage(),
		worktreeFS,
		&git.CloneOptions{URL: "/upstream"},
	); err != nil {
		// ERR: cloning /upstream: repository not found
		t.Fatalf("cloning /upstream: %v", err)
	}
}
```

If there's some other way to effectively clone (besides the `Clone()` function) which works for both go-git->go-git clones as well as `network->go-git` clones, that would meet my need as well.

**Comment by pjbgf** [comment] 2023-08-05 08:46
AFAIK, the support for file-based clone operations is limited, and restricted to OS filesystem. Unfortunately, memFS does not support it.

An alternative would be to expose your upstream repository via a different protocol. For example, turning your upstream on a HTTP web server and cloning it locally. An example of exposing `go-git` repositories as a webserver can be found at: https://github.com/seankhliao/gitreposerver.

Although in this case it would be local traffic, it would still involve some network stack related overhead.

**Comment by weberc2-tempus** [comment] 2023-08-08 14:35
@pjbgf Thanks, I considered this, but was hoping there would be a better way. I'll give it a try, but for the future could this be considered a feature request? Does it align well with the project's goals?

**Comment by pjbgf** [comment] 2023-09-03 20:46
@weberc2-tempus I would be happy to review a PR for a Go native implementation for the `file://` protocol which enables memFS as a source location. Here's where the existing [file protocol implementation](https://github.com/go-git/go-git/tree/master/plumbing/transport/file) lives.

Note that you could implement the new file protocol as a separate Go library and "install it" via [InstallProtocol](https://github.com/go-git/go-git/blob/cd3a21c619126288123c32f4a714181f9e1a68f8/plumbing/transport/client/client.go#L25). The installation part can be seen [in our examples](https://github.com/go-git/go-git/blob/master/_examples/custom_http/main.go#L39). This way you should be able to use it even before it gets merged into the `go-git` repository.

**Comment by jberger-dynatrace** [comment] 2023-09-20 09:59
I think I have a related problem. I create a file system repo locally and clone it also to file system. Which works fine but the problem is that I can't push from the down stream repo with an error `already up-to-date`. I think the problem is that the downstream repo's remate (the upstream repo) has actually the same filesystem as the downstream repo. Any ideas how to hack around this?

**Comment by pjbgf** [comment] 2023-11-04 13:27
@weberc2-tempus you may already be able to do that with something similar to the example in https://github.com/go-git/go-git/issues/838#issuecomment-1793441813.

**Comment by pjbgf** [comment] 2023-11-04 16:51
@weberc2-tempus added an example [here](https://github.com/go-git/go-git/issues/746#issuecomment-1793493794) on cloning from another in-memory repository.

**Comment by pjbgf** [comment] 2024-03-15 23:27
Closing as per examples above and inactivity.

**Closed by pjbgf** 2024-03-15 23:27 UTC
