### ISSUE TITLE
CommitOptions.AllowEmptyCommits does nothing

### ISSUE THREAD

**Issue by akamensky** [go-git/go-git#1058] opened 2024-03-18 22:35 UTC
My code sets

```go
	&git.CommitOptions{
		AllowEmptyCommits: false,
		Author: &object.Signature{
			Name:  author,
			Email: email,
			When:  time.Now(),
		},
	}
```

That however still allows completely empty commits through even if nothing was written. I am cloning to in-memory storage and modify files only if the contents is different (so I read files, on the same note, why is the billy.Filesystem does not implement fs.FS?).

I still have to do `state.IsClean()` check, which will actually check if there are any changes.

**Comment by durvalcarvalho** [comment] 2024-04-09 16:23
Yep! Same thing here.

**Comment by onee-only** [comment] 2024-04-10 02:47
I think this is the same problem as #723.

**Comment by onee-only** [comment] 2024-05-22 23:35
It should be fixed by #1050. Would you check if the problem still exists with code on master @akamensky @durvalcarvalho?

**Comment by akamensky** [comment] 2024-05-22 23:55
I cannot test this for awhile. Hopefully someone else would be able to test. Thanks for fixing it!

**Comment by mostcute** [comment] 2024-12-24 02:22
yes ,fixed but the latest release didn't contain it

**Comment by pjbgf** [comment] 2024-12-28 07:59
Closing as this is in `master` and will soon be part of `v5.13.0`. If the issue is reproduceable on `v5.13.0`, please create a new issue.

**Closed by pjbgf** 2024-12-28 07:59 UTC
