### ISSUE TITLE
Authentication Error: Authentication Required

### ISSUE THREAD

**Issue by Manjinder096** [go-git/go-git#489] opened 2022-03-17 11:50 UTC
Trying to clone a repo using go-git, below is the code that I wrote. I'm using BasicAuth from provided "http" package in go-git. 

```
r, err := git.PlainClone(directory, false, &git.CloneOptions{
		Auth: &http.BasicAuth{
			Username: username,
			Password: password,
		},
		URL:      url,
		Progress: os.Stdout,
	})
```

Also tried using in-memory clone but it also gives same error :

```
r, err := git.Clone(storer, fs, &git.CloneOptions{
		URL:  repository,
		Auth: &http.BasicAuth{
			Username: username,
			Password: password,
		},
	})
```

the error simply says _"authentication required"_ . This is the same method all official examples are also following. Not sure if I am missing anything here ?

**Comment by nathanblair** [comment] 2022-03-18 14:49
I can't say for certain exactly what is causing this but it seems the username and password are required to be valid, though for public repos I haven't confirmed if they auth itself is actually required.

In my case, trying to do a BasicAuth clone from GitHub, it could have something to do with GitHub's git-upload-pack endpoint? It seems to require correct authentication even for a public repository; though running `git fetch` with a URL using dummy credentials at the CLI works fine.

**Comment by lukehinds** [comment] 2023-01-19 09:00
did you figure this out @Manjinder096 

I am getting the same issue using a PAT token.

**Comment by mcepl** [comment] 2024-06-26 18:24
Can I repeat here how much I dislike this stupid bot?

https://drewdevault.com/2021/10/26/stalebot.html

**Comment by pjbgf** [comment] 2024-06-28 20:55
@mcepl do you mind elaborating on the issue you are experiencing? Is this against a specific Git server?

**Comment by mcepl** [comment] 2024-06-29 02:24
I am mostly interested in the fixing of the linked git-bug issue.

**Comment by mcepl** [comment] 2024-07-02 15:15
Just prepared a reproducer for my colleague:

This is my local git repo https://mcepl.fedorapeople.org/tmp/wikipediafs-repo.tar.xz, using https://github.com/MichaelMure/git-bug/releases/download/v0.8.0/git-bug_linux_amd64, and then when I run:

```
tumbleweed-pkg~/r/wikipediafs (master)$ /tmp/git-bug_linux_amd64 push sourcehut
Error: authorization failed
tumbleweed-pkg~/r/wikipediafs (master)$ 
```

(if you want R/W access to the sourcehut repo, let me know your sourcehut username, but I can reproduce exactly the same with https://git.cepl.eu/cgit/toys/wikipediafs/ where it is just `openssh-server-5.3p1-124.el6_10.x86_64` and `git-1.7.1-10.el6_10.x86_64` on an ancient CentOS 6).

**Comment by pjbgf** [comment] 2024-07-13 22:45
@mcepl Thanks for sharing all the details above, that was quite useful. I finally had some time to look into this, and a few things came to mind:

1. `go-bug` is currently using an [older version](https://github.com/MichaelMure/git-bug/blob/6d051a243c734489993c6733c1b21895d59e5e34/go.mod#L19-L20) of `go-git`, which does not include [additional](https://github.com/go-git/go-git/blob/bed3341179a776b47b2507896627960a2871fccd/plumbing/transport/http/common.go#L435) information from such errors.
2. The error you reproduced ([authorization failed](https://github.com/go-git/go-git/blob/bed3341179a776b47b2507896627960a2871fccd/plumbing/transport/http/common.go#L435)) is different than the [authentication required](https://github.com/go-git/go-git/blob/bed3341179a776b47b2507896627960a2871fccd/plumbing/transport/http/common.go#L433), which this issue refers to. On the `git-bug` repo, I also noticed that in the past you also had `ssh: handshake failed: ssh: no authorities for hostname`, but that looks largely orthogonal.

My recommendation would be to build a new version of `git-bug` using `go-git`'s latest version, trying it again and sharing your findings.

One thing to bear in mind is that `go-git` aims to support [Git 2.11](https://github.com/go-git/go-git/blob/bed3341179a776b47b2507896627960a2871fccd/.github/workflows/git.yml#L11) and above. So if the problem is related to the Git server version being very old, it may be harder for us to resolve. However, I am leaning towards this being an issue related to the version of the `openssh` and the supported parameters by the server not supporting the offering parameters from the client - which we should have more control over.

**Comment by mcepl** [comment] 2024-07-14 05:27
I Will look into rebuilding git-bug with revendored dependencies later, but just to note that the reproduction I shown here was against Sourcehut and I don't think they use obsolete software there.

**Comment by mcepl** [comment] 2024-07-14 19:27
When including [this commit](https://git.cepl.eu/cgit/git/git-bug/commit/?id=2b5ce3d2a8ef5685a8fe12a2ab4975ad8fe7a6e2) on the top of the current master, I get [this binary](https://mcepl.fedorapeople.org/tmp/git-bug) for Linux/x86_64. With that I get exactly the same problem:

```sh
tumbleweed-pkg~/r/wikipediafs (master)$ git remote -v
myrepo	https://git.cepl.eu/cgit/toys/wikipediafs (fetch)
myrepo	redcrew:/srv/git/toys/wikipediafs.git (push)
sourcehut	https://git.sr.ht/~mcepl/wikipediafs (fetch)
sourcehut	git@git.sr.ht:~mcepl/wikipediafs (push)
tumbleweed-pkg~/r/wikipediafs (master)$ git bug push sourcehut 
Error: authorization failed
tumbleweed-pkg~/r/wikipediafs (master)$ 
```

(again, trying to push to Sourcehut to eliminate any possible problems with obsolete versions of software on my server)

@MichaelMure, is it possible to get some kind of debugging or verbose information?

**Comment by tomsolem** [comment] 2024-07-26 14:09
I found this issue when I wanted to clone a Github repo over https (due to firewall limitations). 

the basic auth need username and password in the url. i.e. https//user:pwd@server.com/org/repo. The user and password a picked up by the code here: https://github.com/go-git/go-git/blob/ec133065ea1201a4488bbc793ccd9337b6c06877/plumbing/transport/common.go#L226

It seems that it's not possible to use the basic auth or the token auth with a Github app. 
https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app

The workaround is to create a custom http.Client that can set the Authorization token to the request. Based on this:

https://github.com/go-git/go-git/blob/master/_examples/custom_http/main.go

```
type CustomRoundTripper struct {
	Transport http.RoundTripper
	Token     string
}

func (c *CustomRoundTripper) RoundTrip(req *http.Request) (*http.Response, error) {
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", c.Token))
	req.Header.Set("X-GitHub-Api-Version", "2022-11-28")
	return c.Transport.RoundTrip(req)
}

func GetRepo(jwtToken string) {
  customClient := &http.Client{
  Transport: &CustomRoundTripper{
	  Transport: http.DefaultTransport,
	  Token:     jwtToken,
  },
  }
  // Override http(s) default protocol to use our custom client
  client.InstallProtocol("https", githttp.NewClient(customClient))
  
  repo, err := git.PlainClone(dir, false, &git.CloneOptions{
  URL: "https://github.com/org/repo.git",
  })
}
```

**Comment by pjbgf** [comment] 2024-08-08 10:31
While debugging this with @mcepl, we learned that `go-git` currently fails to pick up the push URL from a repository. This is a problem when a HTTPS URL is used for fetch and SSH for push. In this case, no authentication is provided to `go-git` as in theory it should just pick up the SSH configuration. Instead, `go-git` attempts to push to the HTTPS endpoint without an authentication.

**Comment by pjbgf** [comment] 2024-09-25 07:54
Closing this as #1191 is now merged. Given that this issue was capturing more than a single problem, I would rather we create a fresh new issue if new reports arise.

**Closed by pjbgf** 2024-09-25 07:54 UTC
