### ISSUE TITLE
Unable to delete file when the repository will be empty

### ISSUE THREAD

**Issue by Erouan50** [go-git/go-git#723] opened 2023-03-27 21:58 UTC
Hello,

First, thank you for this incredible package!

I get the following error when I try to remove the latest file in a repository and commit:

```
cannot create empty commit: clean working tree
```

I think the issue is due to the index entries being empty when the tree is built here: https://github.com/go-git/go-git/blob/3f1cfde283c93f33218c807602e93d47f72f7b90/worktree_commit.go#L156

Here is a screenshot of my debugging session:

![swappy-20230327-174441](https://user-images.githubusercontent.com/888342/228073968-f9cce632-6605-4406-a745-ebf6d04c31d0.png)

You can see that the index entries are empty, but I have a change staged and ready to be committed.

Here is the code that you can use to reproduce my issue: https://gist.github.com/Erouan50/e2c8ec8d8ad21c7f3761b5f193ab6171#file-main-go

I'll create a pull request if you agree it is a bug.

Thank you!

**Comment by clavinjune** [comment] 2023-06-23 07:03
this is happening on my side too 😢

**Comment by AriehSchneier** [comment] 2023-06-25 02:19
I did a quick test and this is definitely a bug. The issue is that the option `CommitOptions.AllowEmptyCommits` is checking the wrong thing. It is checking if the repo will be empty after the commit rather than the commit not making any changes.

Eg if you modify the test `TestNothingToCommit` and make sure the repo is not empty before running the empty commit tests then the test will fail.

**Comment by clavinjune** [comment] 2023-06-25 19:13
can we use `FileSystem.IsClean()` instead?

**Comment by AriehSchneier** [comment] 2023-06-25 23:50
I can't see that function? I can see [Status.IsClean()](https://github.com/go-git/go-git/blob/master/status.go#L30) however I wouldn't want to require a full status every time we want to commit, I think we need a WorkTree.IsClean() that does the same as WorkTree.Status() but bails out as soon as it finds the first change.

Although WorkTree.Status() is checking both staging and the worktree, I would think we should only need to check staging?

@pjbgf what are your thoughts on this?

**Comment by clavinjune** [comment] 2023-06-26 02:12
something like this @AriehSchneier ?

```go
func (w *Worktree) IsStagingClean() (bool, error) {
	status, err := w.Status()
	if err != nil {
		return false, err
	}

	for _, s := range status {
		if s.Staging != Unmodified {
			return false, nil
		}
	}

	return true, nil
}
```

**Comment by AriehSchneier** [comment] 2023-06-26 02:55
Possibly, I would need to read that code carefully to confirm. However that is doing waaay more work than we would want, and could cause performance issues on large repos (I'm not qualified to know how optimised `w.Status()` is). But I would think we would want to add to `merkletrie` something like:
```
type DiffTreeOptions struct {
	// Should the diff stop after finding the first difference
	OnlyFirstDif bool
}
func DiffTreeContextWithOptions(ctx context.Context, fromTree, toTree noder.Noder,
	hashEqual noder.Equal, options DiffTreeOptions) (Changes, error) {
...
		if options.OnlyFirstDif && len(ret) > 0 {
			return ret, nil
		}
...
}
```
So that we can just search for `any` change... As long as there is 1.

**Comment by g13013** [comment] 2023-07-31 13:51
Hi,

Any updates on this ? for me it's the opposite: AllowEmptyCommits is a NOOP

**Comment by pjbgf** [comment] 2023-09-27 23:08
@Erouan50 thank you for filing the issue and for providing good steps to reproduce. :bow: 

> if you agree it is a bug

I agree this is a bug.

> The issue is that the option `CommitOptions.AllowEmptyCommits` is checking the wrong thing. It is checking if the repo will be empty after the commit rather than the commit not making any changes.

You are absolutely right. 

> I wouldn't want to require a full status every time we want to commit

+1

My suggestion here is that we change the logic to compare the new vs previous Tree hash:

```go
if previousTree == treeHash && (opts == nil || !opts.AllowEmptyCommits) {
	return plumbing.ZeroHash, ErrEmptyCommit
}
```

@AriehSchneier what do you think?

@Erouan50 are you happy to create a PR with the fix? The logic for getting the Tree hash is already within `opts.Amend`.

**Comment by AriehSchneier** [comment] 2023-09-28 06:02
I really don't know the inner working to be able to tell if the tree hash check will be enough.
Although reading the man page for --allow-empty sounds like that is correct:
```
--allow-empty
Usually recording a commit that has the exact same tree as its sole parent commit is a mistake, and the command prevents you from making such a commit. This option bypasses the safety, and is primarily for use by foreign SCM interface scripts.
```

**Comment by ThinkChaos** [comment] 2024-01-25 19:41
Ran into this today. There's a proposed fix above, is there anything holding it back besides motion?

**Comment by AriehSchneier** [comment] 2024-01-25 23:00
@ThinkChaos if you create a PR and test it, I assume it would get merged pretty quickly.

**Closed** 2024-05-22 21:09 UTC
Labels: bug

**Comment by nour-s** [comment] 2024-09-14 20:40
Hi there 👋 

This is still happening today, I downloaded the code referenced in the first post to confirm I'm not doing anything special and I got the same exact result.

I'm using the latest version

``` go.sum
github.com/go-git/gcfg v1.5.1-0.20230307220236-3a3c6141e376 h1:+zs/tPmkDkHx3U66DAb0lQFJrpS6731Oaa12ikc+DiI=
github.com/go-git/gcfg v1.5.1-0.20230307220236-3a3c6141e376/go.mod h1:an3vInlBmSxCcxctByoQdvwPiA7DTK7jaaFDBTtu0ic=
github.com/go-git/go-billy/v5 v5.5.0 h1:yEY4yhzCDuMGSv83oGxiBotRzhwhNr8VZyphhiu+mTU=
github.com/go-git/go-billy/v5 v5.5.0/go.mod h1:hmexnoNsr2SJU1Ju67OaNz5ASJY3+sHgFRpCtpDCKow=
github.com/go-git/go-git/v5 v5.12.0 h1:7Md+ndsjrzZxbddRDZjF14qK+NN56sy6wkqaVrjZtys=
github.com/go-git/go-git/v5 v5.12.0/go.mod h1:FTM9VKtnI2m65hNI/TenDDDnUf2Q9FHnXYjuz9i5OEY=
```

**Comment by AriehSchneier** [comment] 2024-09-16 23:08
> Hi there 👋
> 
> This is still happening today, I downloaded the code referenced in the first post to confirm I'm not doing anything special and I got the same exact result.
> 
> I'm using the latest version
> 
> go.sum:
> 
> ```
> github.com/go-git/gcfg v1.5.1-0.20230307220236-3a3c6141e376 h1:+zs/tPmkDkHx3U66DAb0lQFJrpS6731Oaa12ikc+DiI=
> github.com/go-git/gcfg v1.5.1-0.20230307220236-3a3c6141e376/go.mod h1:an3vInlBmSxCcxctByoQdvwPiA7DTK7jaaFDBTtu0ic=
> github.com/go-git/go-billy/v5 v5.5.0 h1:yEY4yhzCDuMGSv83oGxiBotRzhwhNr8VZyphhiu+mTU=
> github.com/go-git/go-billy/v5 v5.5.0/go.mod h1:hmexnoNsr2SJU1Ju67OaNz5ASJY3+sHgFRpCtpDCKow=
> github.com/go-git/go-git/v5 v5.12.0 h1:7Md+ndsjrzZxbddRDZjF14qK+NN56sy6wkqaVrjZtys=
> github.com/go-git/go-git/v5 v5.12.0/go.mod h1:FTM9VKtnI2m65hNI/TenDDDnUf2Q9FHnXYjuz9i5OEY=
> ```

The fix is on master but no release has been created yet. Try using the master branch.

**Comment by AriehSchneier** [comment] 2024-09-16 23:09
> This is still happening today, I downloaded the code referenced in the first post to confirm I'm not doing anything special and I got the same exact result.
> 
> I'm using the latest version
> 
> go.sum:
> 
> ```
> github.com/go-git/go-git/v5 v5.12.0 h1:7Md+ndsjrzZxbddRDZjF14qK+NN56sy6wkqaVrjZtys=
> github.com/go-git/go-git/v5 v5.12.0/go.mod h1:FTM9VKtnI2m65hNI/TenDDDnUf2Q9FHnXYjuz9i5OEY=
> ```

@nour-s The fix is on master but no release has been created yet. Try using the master branch.

**Comment by nour-s** [comment] 2024-09-17 09:34
@AriehSchneier I see, it is for company production so I would stick with the releases I think. I did a workaround by allowing empty commits.

Thanks for the help
