### ISSUE TITLE
go-git is not "Git implementation in pure Go"

### ISSUE THREAD

**Issue by fiftin** [go-git/go-git#709] opened 2023-03-10 10:09 UTC
Why you call it "pure Go" if you use library https://github.com/pjbgf/sha1cd which written in C?

**Comment by fiftin** [comment] 2023-03-10 10:12
You should change description of the project or remove C dependencies. It will be honest.

**Comment by pjbgf** [comment] 2023-03-11 08:10
The `sha1cd` dependency has both C and Go implementations. As of [v5.6.0](https://github.com/go-git/go-git/releases/tag/v5.6.0), go-git only uses the Go implementation.

Duplicate of #637.

**Comment by pjbgf** [comment] 2023-04-12 19:53
Fixed as per #688.

**Closed by pjbgf** 2023-04-12 19:53 UTC
Labels: duplicate
