### ISSUE TITLE
Symbolic links are mangled when cloning a repository with go-git

### ISSUE THREAD

**Issue by PaulChristophel** [go-git/go-git#689] opened 2023-02-27 19:51 UTC
My sincerest apologies if this is already a known issue or if I am (as is likely) just doing something wrong.

Description:

When cloning or pulling a repository with symbolic links using the go-git package, the links are mangled and point to non-existent paths. For instance, if a repository contains a symbolic link like `/srv/salt/salt-formula/foreman/main/foreman` in a subdirectory `state`, the link is changed to `<clone path>/srv/salt/salt-formula/foreman/main/foreman`, where `<clone path>` is the path where the repository was cloned. This causes the link to point to a non-existent path, which can cause build and runtime errors.

Changing the working dir of the application to `<clone path>` before attempting a force clone/pull also breaks the symlinks, but this time the path is mangled such that the leading `/` is removed.

Steps to reproduce:

Clone a repository that contains symbolic links using the go-git package.
Check the paths of the symbolic links in the cloned repository.

Expected result:

The symbolic links should point to the same paths as in the original repository.

Actual result:

The symbolic links are mangled and point to non-existent paths.

Additional information:

This problem occurs with go-git version v5.5.1 and later.
This problem occurs on the operating system alpine.
This problem does not occur with other Git clients, such as the Git command-line tool or other Git libraries.
This problem is reproducible with repositories that contain symbolic links at different levels of the directory tree.

Workaround:

The workaround for this problem is to use the Git command-line tool or another Git client that does not exhibit this behavior.

**Comment by pjbgf** [comment] 2024-08-23 07:23
Closing as duplicate of #1155. A [workaround](https://github.com/go-git/go-git/issues/1155#issuecomment-2242778023) exists and will be the default behaviour from v6.

**Closed by pjbgf** 2024-08-23 07:23 UTC
