### ISSUE TITLE
Repos with submodules specified by relative URL cannot be cloned

### ISSUE THREAD

**Issue by cy-ddg** [go-git/go-git#266] opened 2021-03-09 08:12 UTC
Trying to clone a repository that is located in `git@gitlab.com:path/to/my/repo.git` (or `https://gitlab.com/path/to/my/repo.git`, doesn't matter) and containing the following `.gitmodules`:
```
[submodule "subpath"]
	path = subpath
	url = ../another/repo.git
```
Results in the error:
```
repository not found
```
The repository `git@gitlab.com:path/to/another/repo.git` or `https://gitlab.com/path/to/another/repo.git` exists and the clone using the git command line tool works.

Are submodules with relative URLs not supported?

**Comment by juanjoku** [comment] 2021-04-22 14:14
Hello,

I have also reproduced that error.
The go-git project has been moved to https://github.com/go-git/go-git, and new version v5.3.0 fixes the bug.

https://github.com/go-git/go-git/releases/tag/v5.3.0  ("Submodule: fix relative submodule resolution")

**Comment by per1234** [comment] 2023-01-11 12:04
As mentioned by **juanjoku**, this was fixed by https://github.com/go-git/go-git/pull/184 + https://github.com/go-git/go-git/pull/195

@cy-ddg please verify the issue is fixed for you and then close the issue.

**Comment by pjbgf** [comment] 2023-11-17 19:52
Closing as fixed as per above. If the issue persists we can always reopen.

**Closed by pjbgf** 2023-11-17 19:52 UTC
