### ISSUE TITLE
Cloning empty repositories

### ISSUE THREAD

**Issue by tommyknows** [go-git/go-git#118] opened 2020-07-02 16:05 UTC
Hi,

When trying to clone an empty repository with `PlainCloneContext`, I get the error:
```
remote repository is empty
```

I guess the error message makes sense, however, a `git clone` on empty repositories works just fine.

Is there a way to work around this behaviour (and just clone the empty repo)? Or is this something that would need to be implemented?

Thanks!

**Comment by 4nte** [comment] 2020-09-06 22:21
It would make sense for an empty dir to be cloned if the repository is empty.

**Comment by akamensky** [comment] 2020-10-20 08:13
This is completely unexpected behavior for which I have to hack a workaround now.

I think this should be classified as a bug.

**Comment by hiddeco** [comment] 2021-02-04 17:44
This is not really a bug in my opinion, but another expectation of what cloning does.

The answer to this is to check the returned `err` for `transport.ErrEmptyRemoteRepository`, when this error is returned you initialize a new repository locally with the remote configured.

On push the branch will be pushed on remote and the repository is no longer empty.

**Comment by stealthybox** [comment] 2021-02-04 23:27
I think it's super reasonable for the library to treat this as a typed error.
Perhaps the examples could be updated with that type-check/init logic, so that this behavior doesn't catch folks by surprise.

**Comment by eduardodicarte** [comment] 2022-04-15 10:27
When creating the repository via REST API, the repository is created empty, so the behavior of cloning an empty repository shouldn't be a mistake, because it's the normal git process.

**Comment by immortalt** [comment] 2023-10-12 07:43
I think this should be classified as a bug.

**Comment by hiddeco** [comment] 2023-10-12 07:58
I continue to be of opinion this is not a bug and can be solved by detecting the error mentioned in https://github.com/go-git/go-git/issues/118#issuecomment-773488577.

**Comment by hiddeco** [comment] 2023-10-12 08:30
To elaborate a bit more on this: when you would clone an empty repository there are is little information available about what to do next, e.g. what should the default branch be?

While `git` has potentially configuration files for this (i.e. `~/.gitconfig`). Programmatically, it is not desired to assume to look for these (by default). Which makes it more desirable to detect this error, and initialize the repository and first branch yourself based on the applicable configuration, than to make certain assumptions (which may result in _other_ unwanted behavior in the end).

**Comment by pjbgf** [comment] 2023-10-13 08:54
Agree with the above, so I will be closing this as it isn't a bug.

**Closed by pjbgf** 2023-10-13 08:54 UTC
